name: CI-CD
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Run Tests
        run: dotnet test devops/devops.csproj --configuration Release
      - name: Deploy to Render
        # We removed the quotes and flags to make it as simple as possible
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
